<?php

class Scanner_Option_TestClass extends ArrayObject implements Scanner_Option_Interface {
    protected $_options;
    
    public function setup($config) {
        $this->_options = $config;
    }
    
    public function setOptions($options) {
        foreach ($options AS $option => $value) {
            $this->setOption($option, $value);
        }
    }
    
    public function getOptions() {
        return (array)$this;
    }
    
    public function setOption($option, $value) {
        $this->offsetSet($option, $value);
    }
    
    public function getOption($option, $default = null) {
        return $this->offsetExists($option) ? $this->offsetGet($option) : $default;
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-08-21 at 09:42:50.
 */
class Scanner_CliHandlerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Scanner_CliHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Scanner_CliHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Scanner_CliHandler::run
     * @todo   Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Scanner_CliHandler::outputUsage
     * @todo   Implement testOutputUsage().
     */
    public function testOutputUsage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
